### PR TITLE
fix Firebird datetime precision

### LINKED ISSUE #273: Microsecond DateTime precision with Firebird 3
Bug report for version 3.1.0.

### Description
The Firebird driver formats full date & time with microsecond precision, but this results in a conversion error when run against a Firebird 3.0.1 server. `TIMESTAMP` in Firebird Dialect 3 (which itself is equivalent to `DATE` in Dialect 1) only supports _decimillisecond_ resolution (10e-4).

### Steps To Reproduce
1. Connect to any Firebird 3 database
2. `$connection->query('SELECT TIMESTAMP %dt AS [t] FROM RDB$DATABASE', new \DateTime());`

### PR DESCRIPTION
**Pull request by jahudka**
- bug fix? yes - fixes #273
- new feature? no
- BC break? no

The Firebird driver formats full date & time with microsecond precision, but this results in a conversion error when run against a Firebird 3.0.1 server. TIMESTAMP in Firebird Dialect 3 (which itself is equivalent to DATE in Dialect 1) only supports decimillisecond resolution (10e-4).

### CODE REVIEW

File: src/Dibi/Drivers/FirebirdDriver.php [hunk 1]
```diff
@@ -284,7 +284,7 @@ public function escapeDateTime($value): string
 		if (!$value instanceof \DateTimeInterface) {
 			$value = new Dibi\DateTime($value);
 		}
-		return $value->format("'Y-m-d H:i:s.u'");
```
Comment (dg) [inline src/Dibi/Drivers/FirebirdDriver.php]: Please use single quotes `'Y-m-d H:i:s.u'` here.

**Comment by dg** [comment]
Thanks!
